# settings.yml
defaults: &defaults
  github:
    token: <%= ENV['GITHUB_APP_ID'] %>
    secret: <%= ENV['GITHUB_SECRET'] %>
  twitter:
    token: <%= ENV['TWITTER_TOKEN'] %>
    secret: <%= ENV['TWITTER_SECRET'] %>

test:
  github:
    token: aaa
    secret: bbb
  twitter:
    token: ccc
    secret: ddd

development:
  <<: *defaults

production:
  <<: *defaults